# Generated by Django 4.2.3 on 2023-07-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
